# Generated by Django 4.1.5 on 2023-01-08 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_remove_post_like_post_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='posts_like',
            field=models.ManyToManyField(blank=True, related_name='posts_like', to='Main.post'),
        ),
    ]
