# Generated by Django 4.1.5 on 2023-01-08 00:47

import Authentication.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', Authentication.models.MyUserManager()),
            ],
        ),
    ]
